# Generated by Django 4.0.4 on 2022-04-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_product_image_remove_review_image_product_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='img',
            new_name='image',
        ),
    ]
