# Generated by Django 4.0.3 on 2022-04-24 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_orderitem_remove_shippingaddress_pobox_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='beforeTaxPrice',
        ),
    ]
