# Generated by Django 4.0.4 on 2022-04-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_alter_order_delivereddate_alter_order_deliverydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/default.png', null=True, upload_to=''),
        ),
    ]
