export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'


export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST'
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS'
export const ORDER_PAYMENT_FAIL = 'ORDER_PAYMENT_FAIL'
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET'

export const ORDER_SHOW_REQUEST = 'ORDER_SHOW_REQUEST'
export const ORDER_SHOW_SUCCESS = 'ORDER_SHOW_SUCCESS'
export const ORDER_SHOW_FAIL = 'ORDER_SHOW_FAIL'
export const ORDER_SHOW_RESET = 'ORDER_SHOW_RESET'


export const ORDER_SHOW_ALL_REQUEST = 'ORDER_SHOW_ALL_REQUEST'
export const ORDER_SHOW_ALL_SUCCESS = 'ORDER_SHOW_ALL_SUCCESS'
export const ORDER_SHOW_ALL_FAIL = 'ORDER_SHOW_ALL_FAIL'

export const ORDER_SHIPPED_REQUEST = 'ORDER_SHIPPED_REQUEST'
export const ORDER_SHIPPED_SUCCESS = 'ORDER_SHIPPED_SUCCESS'
export const ORDER_SHIPPED_FAIL = 'ORDER_SHIPPED_FAIL'
export const ORDER_SHIPPED_RESET = 'ORDER_SHIPPED_RESET'

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST'
export const ORDER_DELIVERED_SUCCESS = 'ORDER_DELIVERED_SUCCESS'
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL'
export const ORDER_DELIVERED_RESET = 'ORDER_DELIVERED_RESET'