export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'

export const USER_LOGOUT_REQUEST='USER_LOGOUT_REQUEST'


export const USER_REGISTER_REQUEST='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL='USER_REGISTER_FAIL'

export const USER_DETAIL_REQUEST='USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS='USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL='USER_DETAIL_FAIL'
export const USER_DETAIL_RESET='USER_DETAIL_RESET'

export const USER_UPDATE_REQUEST='USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS='USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL='USER_UPDATE_FAIL'
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET'

export const USER_DATABASE_REQUEST = 'USER_DATABASE_REQUEST'
export const USER_DATABASE_SUCCESS = 'USER_DATABASE_SUCCESS'
export const USER_DATABASE_FAIL = 'USER_DATABASE_FAIL'
export const USER_DATABASE_RESET = 'USER_DATABASE_RESET'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL'

export const USER_UPDATE_INDIVIDUAL_REQUEST = 'USER_UPDATE_INDIVIDUAL_REQUEST'
export const USER_UPDATE_INDIVIDUAL_SUCCESS = 'USER_UPDATE_INDIVIDUAL_SUCCESS'
export const USER_UPDATE_INDIVIDUAL_FAIL = 'USER_UPDATE_INDIVIDUAL_FAIL'
export const USER_UPDATE_INDIVIDUAL_RESET = 'USER_UPDATE_INDIVIDUAL_RESET'

