const products = [
    {
        'id': '1',
        'name': 'Sony WH-1000XM4',
        'img': '/images/sony-wh1000xm4.jpg',
        'rating': 4.7,
        'reviews': 31469,
        'price': 349.99,
        'inventory': 2000,
        'description': 'Industry-leading noise cancellation technology means you hear every word, note, and tune with incredible clarity, no matter your environment. These noise-canceling headphones feature additional microphones that assist in isolating sound while talking on the phone, resulting in improved phone call quality and the reduction of even more high and mid frequency sounds',
    },
    {
        'id': '2',
        'name': 'Beats Studio 3',
        'img': '/images/beats-studio-3.jpg',
        'rating': 4.7,
        'reviews': 13443,
        'inventory': 2000,
        'price': 229.99,
        'description': 'High-performance wireless noise cancelling headphones',
    },
    {
        'id': '3',
        'name': 'Bose 700',
        'img': '/images/Bose-700.jfif',
        'rating': 4.5,
        'reviews': 22286,
        'inventory': 2000,
        'price': 379.00,
        'description': 'Powerful noise cancelling headphones: 11 levels of active noise cancelling let you enjoy music, podcasts, videos & calls without distractions',
    },
    {
        'id': '4',
        'name': 'Airpod Max',
        'img': '/images/aripod-max.jpg',
        'rating': 4.6,
        'reviews': 2579,
        'inventory': 2000,
        'price': 479.00,
        'description': 'Apple-designed dynamic driver provides high-fidelity audio﻿',
    },
    {
        'id': '5',
        'name': 'Bose QuietComfort 45',
        'img': '/images/bose-45.jpg',
        'rating': 4.7,
        'reviews': 2907,
        'inventory': 2000,
        'price': 329.00,
        'description': 'Noise cancelling wireless headphones – The perfect balance of quiet, comfort, and sound. Bose uses tiny mics to measure, compare, and react to outside noise, cancelling it with opposite signals.﻿',
    },
    {
        'id': '6',
        'name': 'Beats Solo 3',
        'img': '/images/beats-solo3.jfif',
        'rating': 4.7,
        'reviews': 39640,
        'inventory': 2000,
        'price': 149.99,
        'description': 'High-performance wireless Bluetooth headphones in black',
    },
]

export default products 